[workspace]
members = [
  "p2p-repo",
  "p2p-net",
  "p2p-broker",
  "p2p-client-ws",
  "p2p-verifier",
  "stores-rocksdb",
  "ngcli",
  "ngd",
  "ngone",
  "ngaccount",
  "ng-sdk-js",
  "ng-app/src-tauri",
  "ng-wallet"
]

[profile.release]
lto = true
opt-level = 's'

[patch.crates-io]
# tauri = { git = "https://github.com/simonhyll/tauri.git",  branch="fix/ipc-mixup"}
# tauri = { git = "https://git.nextgraph.org/NextGraph/tauri.git", branch="alpha.11-nextgraph", features = ["no-ipc-custom-protocol"] }