[workspace]
members = [
  "p2p-repo",
  "p2p-net",
  "p2p-broker",
  "p2p-client",
  "p2p-verifier",
  "p2p-stores-lmdb",
  "ngcli",
  "ngd",
  "ng-app-js",
]

[profile.release]
lto = true
opt-level = 's'