[workspace]
members = [
  "p2p-repo",
  "p2p-net",
  "p2p-broker",
  "p2p-client-ws",
  "p2p-verifier",
  "stores-lmdb",
  "ngcli",
  "ngd",
  "ngone",
  "ng-app-js",
  "ng-app-native/src-tauri",
  "ng-wallet"
]

[profile.release]
lto = true
opt-level = 's'