packages:
    - sdk/js/lib-wasm/pkg
    - sdk/js/api
    - sdk/js/api-web
    - sdk/js/web
    - sdk/js/frontend
    - sdk/js/auth-ldo-react
    - sdk/js/orm
    - sdk/js/alien-deepsignals
    - sdk/js/shex-orm
    - sdk/js/examples/expense-tracker-discrete
    - sdk/js/examples/expense-tracker-rdf
    - sdk/js/examples/react-ldo
    - sdk/js/examples/test-react-sdk
    - sdk/js/examples/remote-react-microapp
    - app/ui-common
    - app/shell
    - app/docs
    - app/calc
    - engine/broker/auth
    - infra/ngaccount/web
    - infra/ngapp/web
    - infra/ngnet/bootstrap
    - infra/ngnet/redir
    - infra/ngnet/web
    - infra/ngnet/auth
onlyBuiltDependencies:
    - "@parcel/watcher"
    - "@swc/core"
    - es5-ext
    - esbuild
    - svelte-preprocess
