packages:
    - sdk/js/lib-wasm/pkg
    - sdk/js/api-web
    - sdk/js/signals
    - sdk/js/alien-deepsignals
    - sdk/js/shex-orm
    - sdk/js/examples/multi-framework-signals
    - app/ui-common
    - app/nextgraph
    - engine/broker/auth
    - infra/ngaccount/web
    - infra/ngapp/web
    - infra/ngnet/bootstrap
    - infra/ngnet/redir
onlyBuiltDependencies:
    - "@parcel/watcher"
    - "@swc/core"
    - es5-ext
    - esbuild
    - svelte-preprocess
