// Copyright (c) 2025 Laurin Weger, Par le Peuple, NextGraph.org developers
// All rights reserved.
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE2 or http://www.apache.org/licenses/LICENSE-2.0>
// or the MIT license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.
// SPDX-License-Identifier: Apache-2.0 OR MIT

import type { BaseType } from "@ng-org/shex-orm";
import { useDeepSignal } from "@ng-org/alien-deepsignals/react";
import type { ShapeType } from "@ng-org/shex-orm";
import { useEffect, useMemo, useRef, useState } from "react";
import { normalizeConf } from "../../types.ts";
import {
    RdfOrmSubscription,
    RdfOrmSubscriptionFor,
} from "../../connector/RdfOrmSubscription.ts";
import type { DeepSignalSet, DeepSignal } from "@ng-org/alien-deepsignals";
import { RdfOrmConfig, SubscriptionData } from "../../utilTypes.ts";

const EMPTY_OBJECT = {} as const;

/**
 * Hook to subscribe to RDF data in the graph database using a shape, see {@link ShapeType}.
 *
 * Establishes a 2-way binding with the returned data: Modifications to the data are automatically committed,
 * changes coming from the engine (or other components) cause an immediate rerender.
 *
 * @param shape The {@link ShapeType} the objects should have (generated by the shex-orm tool).
 * @param conf The config that can be a document nuri, {@link RdfOrmConfig} or undefined.
 * @returns A {@link UseShapeResult} with the orm objects or an empty set, if still loading.\
 *          If the conf is explicitly set to `undefined`, the returned data is `undefined` and `isLoading` is false.
 *
 * @example
 * ```tsx
 * function Expenses() {
 *     const { data: expenses, isLoading }: DeepSignal<Set<Expense>> = useShape(
 *         ExpenseShapeType,
 *         {
 *             graphs: ["<document NURI>"]
 *             orderBy: {dateOrPurchase: "desc"}
 *         }
 *     );
 *
 *     const createExpense = useCallback(
 *         () => {
 *             expenses.add({
 *                 "@graph": `<document NURI>`,
 *                 "@type": "did:ng:z:Expense",
 *                 "@id": "", // Assigns ID automatically, if set to "".
 *                 title: "New expense",
 *                 dateOfPurchase: obj.dateOfPurchase ?? new Date().toISOString(),
 *             });
 *         },
 *         [expenses]
 *     );
 *
 *     return (
 *         <div>
 *             <button
 *                 onClick={() => createExpense({})}
 *             >
 *                 + Add expense
 *             </button>
 *             <div>
 *                 {isLoading && (
 *                     <p>
 *                         Loading...
 *                     </p>
 *                 )}
 *                 {expenses && expenses.size === 0 && (
 *                     <p>
 *                         No expenses yet.
 *                     </p>
 *                 )}
 *                 {expenses && expenses.size > 0 && (
 *                     [...expenses].map((expense) => (
 *                         // You can modify the expense's properties in the ExpenseCard component
 *                         // which will instantly trigger a rerender.
 *                         <ExpenseCard
 *                             key={expense["@id"]}
 *                             expense={expense}
 *                         />
 *                     ))
 *                 )}
 *             </div>
 *         </div>
 *     );
 * }
 * ```
 */
const useShape = <
    ST extends ShapeType<T>,
    const CONF extends RdfOrmConfig<T>,
    T extends BaseType = ST extends ShapeType<infer T_> ? T_ : never,
    SUBSCRIPTION_DATA = SubscriptionData<T, CONF>,
>(
    shape: ST,
    conf: CONF | string | undefined
): UseShapeResult<ST, CONF, T> => {
    const dependencies = [
        typeof conf,
        JSON.stringify((conf as CONF)?.graphs),
        JSON.stringify((conf as CONF)?.subjects),
        (conf as CONF)?.maxActivePages,
        (conf as CONF)?.pageSize,
        JSON.stringify((conf as CONF)?.orderBy),
    ];
    const parsedConf = useMemo(
        () => (!conf ? undefined : normalizeConf(conf)),
        dependencies
    );
    const [isReady, setIsReady] = useState(false);

    const ormSubscription = useMemo(() => {
        if (parsedConf === undefined) return undefined;

        const newOrmSubscription = RdfOrmSubscription.getOrCreate(
            shape,
            parsedConf
        );

        return newOrmSubscription;
    }, dependencies);

    useEffect(() => {
        if (!ormSubscription) return;

        ormSubscription?.readyPromise.then(() => {
            setIsReady(true);
        });

        return () => {
            setIsReady(false);
            ormSubscription.close();
        };
    }, [ormSubscription]);

    // If no data has arrived or the scope is unset, use a dummy object
    // that won't be returned (useDeepSignal requires some kind of data).
    const state = useDeepSignal(
        ormSubscription && isReady
            ? ormSubscription.signalObject
            : EMPTY_OBJECT,
        {
            replaceProxiesInBranchOnChange: true,
        }
    );

    const nextPage =
        ormSubscription?.mode === "orderedPaginatedCumulative" ||
        ormSubscription?.mode === "orderedPaginatedSimple"
            ? // @ts-ignore
              ormSubscription.nextPage
            : undefined;
    const previousPage =
        ormSubscription?.mode === "orderedPaginatedSimple"
            ? // @ts-ignore
              ormSubscription.previousPage
            : undefined;

    // @ts-ignore
    return {
        data: (isReady ? state : undefined) as SUBSCRIPTION_DATA,
        isLoading: !ormSubscription ? false : ormSubscription.isReady,
        promise: ormSubscription?.readyPromise,
        subscription: ormSubscription,
        nextPage,
        previousPage,
    };
};

export default useShape;

type UseShapeResult_<
    ST extends ShapeType<any>,
    CONF extends RdfOrmConfig<T>,
    T extends BaseType,
    SUBSCRIPTION_DATA = SubscriptionData<T, CONF>,
> = {
    /**
     * Initializes loading of the next page.
     * This will update the data but you will not be called back on it.
     */
    nextPage: () => void;
    /**
     * Initializes loading of the previous page.
     * This will update the data but you will not be called back on it.
     */
    previousPage: () => void;
    /**
     * `true` when no data is available yet and `conf` is not `undefined`.
     *
     * It is *not* set to `true` while loading pages (through `nextPage()` or `previousPage()`.
     */
    isLoading: boolean;
    /**
     * The requested data, once loaded.
     * Depending on your orderBy config, this will either be a {@link DeepSignalSet}
     * or a [`DeepSignal<ReadOnlyArray>`]({@link DeepSignal}) (you can modify its properties and sub-objects though).
     *
     * This object is the value returned by {@link RdfOrmSubscription.signalObject} with the following exception:
     * To capture modifications to it in react, the root is a proxy that is replaced on every relevant rerender.
     */
    data: SUBSCRIPTION_DATA | undefined;
    /**
     * A promise that resolves once the data is loaded.
     * Note that if `conf` is `undefined`, this property is `undefined`.
     */
    promise: CONF extends undefined ? undefined : Promise<SUBSCRIPTION_DATA>;
    /** The underlying {@link RdfOrmSubscription} through which the data is loaded. */
    subscription: CONF extends undefined
        ? undefined
        : RdfOrmSubscriptionFor<ST, CONF, T>;
};

export type UseShapeResult<
    ST extends ShapeType<any>,
    CONF extends RdfOrmConfig<T>,
    T extends BaseType,
> = undefined extends CONF["pageSize"]
    ? Omit<UseShapeResult_<ST, CONF, T>, "nextPage" | "previousPage"> // No pagination functions.
    : undefined extends CONF["maxActivePages"]
      ? Omit<UseShapeResult_<ST, CONF, T>, "previousPage"> // Only forward pagination without `maxActivePages`.
      : UseShapeResult_<ST, CONF, T>; // Forward and backwards pagination.
