// Copyright (c) 2025 Laurin Weger, Par le Peuple, NextGraph.org developers
// All rights reserved.
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE2 or http://www.apache.org/licenses/LICENSE-2.0>
// or the MIT license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.
// SPDX-License-Identifier: Apache-2.0 OR MIT

import { normalizeConf, type Scope } from "../../types.ts";
import { useDeepSignal } from "@ng-org/alien-deepsignals/vue";
import { onBeforeUnmount, Ref, ref, shallowRef } from "vue";
import type { BaseType, ShapeType } from "@ng-org/shex-orm";
import {
    RdfOrmSubscription,
    RdfOrmSubscriptionFor,
} from "../../connector/RdfOrmSubscription.ts";
import { DeepSignalSet, DeepSignal } from "@ng-org/alien-deepsignals";
import { RdfOrmConfig, SubscriptionData } from "../../utilTypes.ts";

/**
 * Hook to subscribe to RDF data in the graph database using a shape, see {@link ShapeType}.
 * The returned objects are as easy to use as other TypeScript objects.
 *
 * Returns a {@link DeepSignalSet} of objects matching the shape and that are within the scope.
 * Establishes a 2-way binding: Modifications to the object are immediately committed,
 * changes coming from the backend (or other components) cause an immediate rerender.
 *
 * @param shape The {@link ShapeType} the objects should have (generated by the shex-orm tool).
 * @param scope The {@link Scope} as graph string or scope object with graphs and subjects.
 * @returns A {@link DeepSignalSet} with the orm objects or an empty set, if still loading.\
 *          If the scope is explicitly set to `undefined`, an empty set is returned which errors
 *          if you try to make modifications on it.
 *
 * @example
 * ```html
 * <script lang="ts">
 * // Contains all expense objects with `@id` <s1 IRI> or <s2 IRI> and `@graph` <g1 NURI> or <g2 NURI>
 * const { data: expenses, isLoading }: DeepSignal<Set<Expense>> = useShape(ExpenseShapeType,
 *      {graphs: ["<g1 NURI>", "<g2 NURI>"],
 *       subjects: ["<s1 IRI>", "<s2 IRI>"]});
 *
 *
 *
 * // Simply call expenses.add({"@graph": "<g1 or g2 NURI>", "@id": "", title: "Example title"}), to add new elements.
 * // Leave `@id` an empty string to auto-generate a subject NURI (adjust your scope accordingly).
 *
 * </script>
 *
 * <template>
 *     <div>
 *         <p v-if="isLoading">
 *             No expenses yet.
 *         </p>
 *         <p v-else-if="expenses.size === 0">
 *             No expenses yet.
 *         </p>
 *         <template v-else>
 *             <ExpenseCard
 *                 v-for="expense in expenses"
 *                 :key="expense['@id'])"
 *                 :expense="expense"
 *             />
 *         </template>
 *     </div>
 * </template>
 * ```
 *
 * In the `ExpenseCard` component:
 * ```html
 * <script lang="ts">
 * const { expense } = defineProps<{
 *     expense: DeepSignal<Expense>;
 * }>();
 *
 * // If you modify expense in the component,
 * // the changes are immediately propagated to other consuming components.
 * // And persisted in the database.
 * </script>
 *
 * <template>
 *     <input
 *         v-model="expense.title"
 *         placeholder="Expense title"
 *     />
 * </template>
 * ```
 */
const useShape = <
    ST extends ShapeType<T>,
    const CONF extends RdfOrmConfig<T>,
    T extends BaseType = ST extends ShapeType<infer T_> ? T_ : never,
    SUBSCRIPTION_DATA = SubscriptionData<T, CONF>,
>(
    shape: ST,
    conf: CONF | string | undefined
): UseShapeResult<ST, CONF, T> => {
    if (conf === undefined) {
        return {
            data: ref(undefined),
            isLoading: ref(false),
            promise: undefined,
            subscription: undefined,
        } as UseShapeResult<ST, CONF, T>;
    }

    const parsedConf = normalizeConf(conf);

    const subscription = RdfOrmSubscription.getOrCreate(shape, parsedConf);

    onBeforeUnmount(() => {
        subscription.close();
    });

    const nextPage =
        subscription?.mode === "orderedPaginatedCumulative" ||
        subscription?.mode === "orderedPaginatedSimple"
            ? // @ts-ignore
              subscription.nextPage
            : undefined;
    const previousPage =
        subscription?.mode === "orderedPaginatedSimple"
            ? // @ts-ignore
              subscription.previousPage
            : undefined;

    const data = useDeepSignal(subscription.signalObject);

    const dataRef = shallowRef(subscription.isReady ? data : undefined);
    const isLoadingRef = ref(!subscription.isReady);

    subscription.readyPromise.then(() => {
        dataRef.value = subscription.signalObject;
        isLoadingRef.value = false;
    });

    return {
        nextPage,
        previousPage,
        promise: subscription.readyPromise,
        subscription,
        data: dataRef,
        isLoading: isLoadingRef,
    } as UseShapeResult<ST, CONF, T>;
};

export default useShape;

type UseShapeResult_<
    ST extends ShapeType<any>,
    CONF extends RdfOrmConfig<T>,
    T extends BaseType,
    SUBSCRIPTION_DATA = SubscriptionData<T, CONF>,
> = {
    /**
     * Initializes loading of the next page.
     * This will update the data but you will not be called back on it.
     */
    nextPage: () => void;
    /**
     * Initializes loading of the previous page.
     * This will update the data but you will not be called back on it.
     */
    previousPage: () => void;
    /**
     * `true` when no data is available yet and `conf` is not `undefined`.
     *
     * It is *not* set to `true` while loading pages (through `nextPage()` or `previousPage()`.
     */
    isLoading: Ref<boolean>;
    /**
     * The requested data, once loaded. While still loading, `data` wil be empty.
     *
     * Depending on your orderBy config, this will either be a {@link DeepSignalSet}
     * or a [`DeepSignal<ReadOnlyArray>`]({@link DeepSignal}) (you can modify its properties and sub-objects though).
     *
     * This object is the value returned by {@link RdfOrmSubscription.signalObject}.
     */
    data: Ref<SUBSCRIPTION_DATA | undefined>;
    /**
     * A promise that resolves once the data is loaded.
     * Note that if `conf` is `undefined`, this property is `undefined`.
     */
    promise: CONF extends undefined ? undefined : Promise<SUBSCRIPTION_DATA>;
    /** The underlying {@link RdfOrmSubscription} through which the data is loaded. */
    subscription: CONF extends undefined
        ? undefined
        : RdfOrmSubscriptionFor<ST, CONF, T>;
};

export type UseShapeResult<
    ST extends ShapeType<any>,
    CONF extends RdfOrmConfig<T>,
    T extends BaseType,
> = undefined extends CONF["pageSize"]
    ? Omit<UseShapeResult_<ST, CONF, T>, "nextPage" | "previousPage"> // No pagination functions.
    : undefined extends CONF["maxActivePages"]
      ? Omit<UseShapeResult_<ST, CONF, T>, "previousPage"> // Only forward pagination without `maxActivePages`.
      : UseShapeResult_<ST, CONF, T>; // Forward and backwards pagination.
