// Copyright (c) 2025 Laurin Weger, Par le Peuple, NextGraph.org developers
// All rights reserved.
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE2 or http://www.apache.org/licenses/LICENSE-2.0>
// or the MIT license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.
// SPDX-License-Identifier: Apache-2.0 OR MIT

import type { Scope } from "../../types.ts";
import { useDeepSignal } from "@ng-org/alien-deepsignals/vue";
import { onBeforeUnmount } from "vue";
import type { BaseType, ShapeType } from "@ng-org/shex-orm";
import { OrmConnection } from "../../connector/ormConnectionHandler.ts";
import { DeepSignalSet } from "@ng-org/alien-deepsignals";

/**
 * Hook to subscribe to RDF data in the graph database using a shape, see {@link ShapeType}.
 * The returned objects are as easy to use as other TypeScript objects.
 *
 * Returns a {@link DeepSignalSet} of objects matching the shape and that are within the scope.
 * Establishes a 2-way binding: Modifications to the object are immediately committed,
 * changes coming from the engine (or other components) cause an immediate rerender.
 *
 * @param shape The {@link ShapeType} the objects should have (generated by the `@ng-org/shex-orm` tool).
 * @param scope The scope in which the objects should be.
 * @returns A {@link DeepSignalSet} containing the objects matching the shape type and scope.
 *
 * @example
 * ```html
 * <script lang="ts">
 * // Contains all expense objects with `@id` <s1 IRI> or <s2 IRI> and `@graph` <g1 IRI> or <g2 IRI>
 * const expenses: DeepSignalSet<Expense> = useShape(ExpenseShapeType,
 *      {graphs: ["<g1 IRI>", "<g2 IRI>"],
 *       subjects: ["<s1 IRI>", "<s2 IRI>"]});
 *
 *
 * const expensesSorted = computed(() => [...expenses].sort((a, b) =>
 *     a.dateOfPurchase.localeCompare(b.dateOfPurchase)
 * ));
 *
 * // Simply call expenses.add({"@graph": "<g1 or g2 IRI>", "@id": "", title: "Example title"}), to add new elements.
 * // Leave `@id` an empty string to auto-generate a subject IRI (adjust your scope accordingly).
 *
 * // Note that if you use `@id` (the subject IRI) as key, you need to ensure that it is unique within your scope.
 * // If it is not, use the combination of `@graph` and `@id`.
 * </script>
 *
 * <template>
 *     <div>
 *         <p v-if="expensesSorted.length === 0">
 *             No expenses yet.
 *         </p>
 *         <template v-else>
 *             <ExpenseCard
 *                 v-for="expense in expensesSorted"
 *                 :key="expense['@id'])"
 *                 :expense="expense"
 *             />
 *         </template>
 *     </div>
 * </template>
 * ```
 *
 * In the `ExpenseCard` component:
 * ```html
 * <script lang="ts">
 * const props = defineProps<{
 *     expense: DeepSignal<Expense>;
 * }>();
 *
 * // Important!
 * // In vue, you need to wrap children into useDeepSignal hooks,
 * // to ensure the component re-renders on changes coming from
 * // other components or the backend.
 * const expense = useDeepSignal(props.expense);
 *
 * // If you modify expense in the component,
 * // the changes are immediately propagated to the other components
 * // And persisted in the database.
 * </script>
 *
 * <template>
 *     <input
 *         v-model="expense.title"
 *         placeholder="Expense title"
 *     />
 * </template>
 * ```
 */
export function useShape<T extends BaseType>(
    shape: ShapeType<T>,
    scope: Scope = {}
) {
    const connection = OrmConnection.getOrCreate(shape, scope);

    // Cleanup
    onBeforeUnmount(() => {
        connection.close();
    });

    const ref = useDeepSignal(connection.signalObject);

    return ref;
}

export default useShape;
