/**
 * Deep clone function with support for Sets and Maps.
 * Function generated by Claude Opus 4.5
 */
export const deepClone = <T>(object: T, seen = new WeakMap()): T => {
    // Handle primitives and null
    if (object === null || typeof object !== "object") {
        return object;
    }

    // Handle circular references
    if (seen.has(object)) {
        return seen.get(object);
    }

    // Handle Date
    if (object instanceof Date) {
        return new Date(object.getTime()) as T;
    }

    // Handle Set
    if (object instanceof Set) {
        const clonedSet = new Set();
        seen.set(object, clonedSet);
        for (const item of object) {
            clonedSet.add(deepClone(item, seen));
        }
        return clonedSet as T;
    }

    // Handle Map
    if (object instanceof Map) {
        const clonedMap = new Map();
        seen.set(object, clonedMap);
        for (const [key, value] of object) {
            clonedMap.set(deepClone(key, seen), deepClone(value, seen));
        }
        return clonedMap as T;
    }

    // Handle Array
    if (Array.isArray(object)) {
        const clonedArray: any[] = [];
        seen.set(object, clonedArray);
        for (const item of object) {
            clonedArray.push(deepClone(item, seen));
        }
        return clonedArray as T;
    }

    // Handle plain objects
    const clonedObject: Record<string, any> = {};
    seen.set(object, clonedObject);
    for (const key of Object.keys(object)) {
        clonedObject[key] = deepClone(
            (object as Record<string, any>)[key],
            seen
        );
    }
    return clonedObject as T;
};
