[package]
name = "lib-wasm"
version = "0.1.2"
description = "JS app SDK of NextGraph"
publish = false
# version.workspace = true
edition.workspace = true
license = "MIT/Apache-2.0"
authors.workspace = true
repository = "https://git.nextgraph.org/NextGraph/nextgraph-rs" 
homepage = "https://nextgraph.org"
keywords.workspace = true
documentation.workspace = true
rust-version.workspace = true

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = false

[package.metadata.scripts]
appdev = "wasm-pack build --dev --target bundler && node prepare-web.js"
appdev3 = "wasm-pack build --profiling --target bundler && node prepare-web.js"
app = "rm -rf pkg/snippets & rmdir pkg\\snippets /s /q & wasm-pack build --target bundler && node prepare-web.js"
nodedev = "rm -rf pkg-node/snippets & rmdir pkg\\snippets /s /q & wasm-pack build --dev -t nodejs -d pkg-node && node prepare-node.js"
node = "rm -rf pkg-node/snippets & rmdir pkg\\snippets /s /q & wasm-pack build -t nodejs -d pkg-node && node prepare-node.js"
web = "rm -rf web/snippets & rmdir pkg\\snippets /s /q & wasm-pack build --target web -d web"
webdev = "rm -rf web/snippets  & rmdir pkg\\snippets /s /q & wasm-pack build --dev --target web -d web"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_bare = "0.5.0"
serde_bytes = "0.11.7"
async-std = {  version = "1.12.0", features = ["attributes","unstable"] }
once_cell = "1.17.1"
getrandom = { version = "0.3", features = ["wasm_js"] }
rand = { version = "0.7", features = ["getrandom"] }
uuid = { version = "1.18.1", features = ["rng-getrandom"] }
wasm-bindgen = { version = "0.2.88", features = ["serde-serialize"] }
sys-locale = { version = "0.3.1", features = ["js"] }
futures = "0.3.24"
ng-repo = { path = "../../../engine/repo" }
ng-net = { path = "../../../engine/net" }
ng-client-ws = { path = "../../../engine/client-ws" }
ng-wallet = { path = "../../../engine/wallet" }
nextgraph = { path = "../../rust" }
oxrdf = { git = "https://git.nextgraph.org/NextGraph/oxigraph.git",  branch="main", features = ["rdf-star", "oxsdatatypes"] }


[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.61"
serde-wasm-bindgen = "0.6"
wasm-bindgen-futures = "0.4.50"
gloo-timers = "0.3.0"
# web-sys = { version = "0.3.61", features = ["Window"] }

[dev-dependencies]
wasm-bindgen-test = "^0.3"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(wasmpack_target, values("nodejs"))'] }