// Copyright (c) 2025 Laurin Weger, Par le Peuple, NextGraph.org developers
// All rights reserved.
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE2 or http://www.apache.org/licenses/LICENSE-2.0>
// or the MIT license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.
// SPDX-License-Identifier: Apache-2.0 OR MIT

import { normalizeConf, type Scope } from "../../types.ts";
import { onDestroy } from "svelte";
import type { BaseType, ShapeType } from "@ng-org/shex-orm";
import { DeepSignalSet, DeepSignal } from "@ng-org/alien-deepsignals";
import { useDeepSignal } from "@ng-org/alien-deepsignals/svelte";
import {
    RdfOrmSubscription,
    RdfOrmSubscriptionFor,
} from "../../connector/RdfOrmSubscription.ts";
import { RdfOrmConfig, SubscriptionData } from "../../utilTypes.ts";
import { setRawPrototype } from "../utils.ts";

/**
 * Svelte 5 hook to subscribe to RDF data in the graph database using a shape, see {@link ShapeType}.
 *
 * Returns a {@link DeepSignalSet} that contain the objects matching the shape and that are within the scope.
 * Establishes a 2-way binding: Modifications to the object are immediately committed,
 * changes coming from the engine (or other components) cause an immediate rerender.
 *
 * @param shape The {@link ShapeType} the objects should have (generated by the `@ng-org/shex-orm` tool).
 * @param conf The {@link RdfOrmConfig} or a graph string.
 * @returns A {@link DeepSignalSet} with the orm objects or an empty set, if still loading.\
 *          If the scope is explicitly set to `undefined`, an empty set is returned which errors
 *          if you try to make modifications on it.
 *
 * @example
 * ```svelte
 * <script lang="ts">
 *     // Gets all expense objects with `@id` <s1 IRI> or <s2 IRI> and `@graph` <g1 NURI> or <g2 NURI>
 *     const { data: expenses, isLoading } = $derived(
 *         useShape(ExpenseShapeType,
 *             {graphs: ["<g1 NURI>", "<g2 NURI>"],
 *             subjects: ["<s1 NURI>", "<s2 NURI>"]}));
 *     // `expenses` has type `DeepSignal<Set<Expense>>`
 *
 *     const createExpense = () => {
 *         expenses.add({
 *             "@graph": `<graph NURI>`,
 *             "@type": "did:ng:z:Expense",
 *             "@id": "", // Assign ID automatically.
 *             title: "New expense",
 *             dateOfPurchase: obj.dateOfPurchase ?? new Date().toISOString(),
 *         });
 *     };
 *
 * </script>
 *
 * <section>
 *     <div>
 *         <button on:click={() => createExpense()}>
 *             + Add expense
 *         </button>
 *
 *         {# if isLoading}
 *             <p>
 *                 Loading...
 *             </p>
 *         {:else if expenses.size === 0}
 *             <p>
 *                 No expense yet.
 *             </p>
 *         {:else}
 *             {#each expenses as expense, index (expense['@id']) }
 *                 <ExpenseCard
 *                     expense={expense}
 *                 />
 *             {/each}
 *         {/if}
 *     </div>
 * </section>
 * ```
 *
 * ---
 * In the ExpenseCard component:
 * ```svelte
 * <script lang="ts">
 * let {
 *     expense,
 * }: { expense: DeepSignal<Expense>; } = $props();
 * </script>
 *
 * <div>
 *     <input
 *         bind:value={expense.title}
 *     />
 * </div>
 * ```
 */
const useShape = <
    ST extends ShapeType<T>,
    const CONF extends RdfOrmConfig<T>,
    T extends BaseType = ST extends ShapeType<infer T_> ? T_ : never,
>(
    shape: ST,
    conf: CONF | string | undefined
): UseShapeResult<ST, CONF, T> => {
    if (conf === undefined) {
        // @ts-ignore
        return {
            data: undefined,
            promise: undefined,
            subscription: undefined,
        };
    }

    const parsedConf = normalizeConf(conf);

    const subscription = RdfOrmSubscription.getOrCreate(shape, parsedConf);

    onDestroy(subscription.close);

    const nextPage =
        subscription?.mode === "orderedPaginatedCumulative" ||
        subscription?.mode === "orderedPaginatedSimple"
            ? // @ts-ignore
              subscription.nextPage
            : undefined;
    const previousPage =
        subscription?.mode === "orderedPaginatedSimple"
            ? // @ts-ignore
              subscription.previousPage
            : undefined;

    let data = useDeepSignal(subscription.signalObject);
    // Prevent data from being proxied by modifying its prototype.
    setRawPrototype(data);

    let ret = $state({
        nextPage,
        previousPage,
        isLoading: !subscription.isReady,
        promise: subscription.readyPromise,
        subscription,
        data,
    });

    subscription.readyPromise.then(() => {
        ret.isLoading = false;
        ret.data = data as any;
    });

    // @ts-ignore
    return ret;
};

export default useShape;

type UseShapeResult_<
    ST extends ShapeType<any>,
    CONF extends RdfOrmConfig<T>,
    T extends BaseType,
    SUBSCRIPTION_DATA = SubscriptionData<T, CONF>,
> = {
    /**
     * Initializes loading of the next page.
     * This will update the data but you will not be called back on it.
     */
    nextPage: () => void;
    /**
     * Initializes loading of the previous page.
     * This will update the data but you will not be called back on it.
     */
    previousPage: () => void;
    /**
     * `true` when no data is available yet and `conf` is not `undefined`.
     *
     * It is *not* set to `true` while loading pages (through `nextPage()` or `previousPage()`.
     */
    isLoading: boolean;
    /**
     * The requested data. While still loading, data is undefined.
     *
     * Depending on your orderBy config, this will either be a {@link DeepSignalSet}
     * or a [`DeepSignal<ReadOnlyArray>`]({@link DeepSignal}) (you can modify its properties and sub-objects though).
     *
     * Once loaded, this object is the value returned by {@link RdfOrmSubscription.signalObject}.
     */
    data: SUBSCRIPTION_DATA;
    /**
     * A promise that resolves once the data is loaded.
     * Note that if `conf` is `undefined`, this property is `undefined`.
     */
    promise: CONF extends undefined ? undefined : Promise<SUBSCRIPTION_DATA>;
    /** The underlying {@link RdfOrmSubscription} through which the data is loaded. */
    subscription: CONF extends undefined
        ? undefined
        : RdfOrmSubscriptionFor<ST, CONF, T>;
};

export type UseShapeResult<
    ST extends ShapeType<any>,
    CONF extends RdfOrmConfig<T>,
    T extends BaseType,
> = undefined extends CONF["pageSize"]
    ? Omit<UseShapeResult_<ST, CONF, T>, "nextPage" | "previousPage"> // No pagination functions.
    : undefined extends CONF["maxActivePages"]
      ? Omit<UseShapeResult_<ST, CONF, T>, "previousPage"> // Only forward pagination without `maxActivePages`.
      : UseShapeResult_<ST, CONF, T>; // Forward and backwards pagination.
