// Copyright (c) 2025 Laurin Weger, Par le Peuple, NextGraph.org developers
// All rights reserved.
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE2 or http://www.apache.org/licenses/LICENSE-2.0>
// or the MIT license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.
// SPDX-License-Identifier: Apache-2.0 OR MIT

import { normalizeConf, normalizeScope, type Scope } from "../../types.ts";
import { onDestroy } from "svelte";
import type { BaseType, ShapeType } from "@ng-org/shex-orm";
import {
    useDeepSignal,
    type UseDeepSignalResult,
} from "@ng-org/alien-deepsignals/svelte4";
import { DeepSignalSet } from "@ng-org/alien-deepsignals";
import {
    RdfOrmSubscription,
    RdfOrmSubscriptionFor,
} from "../../connector/RdfOrmSubscription.ts";
import { readOnlySet } from "../utils.ts";
import { RdfOrmConfig, SubscriptionData } from "../../utilTypes.ts";
import { derived, writable } from "svelte/store";

/** Extended result including the originating root signal wrapper from shape logic. @ignore*/
export interface UseShapeStoreResult<T = object>
    extends UseDeepSignalResult<T> {
    root: any;
}

/**
 * Svelte 4 hook to subscribe to RDF data in the graph database using a shape, see {@link ShapeType}.
 *
 * Returns a {@link DeepSignalSet} store containing the objects matching the shape and that are within the scope.
 * Establishes a 2-way binding: Modifications to the object are immediately committed,
 * changes coming from the backend (or other components) cause an immediate rerender.
 *
 * @param shape The {@link ShapeType} the objects should have (generated by the shex-orm tool).
 * @param scope The {@link Scope} as graph string or scope object with graphs and subjects.
 * @returns A {@link DeepSignalSet} with the orm objects or an empty set, if still loading.\
 *          If the scope is explicitly set to `undefined`, an empty set is returned which errors
 *          if you try to make modifications on it.
 *
 * @example
 * ```svelte
 * <script lang="ts">
 *     // Gets all expense objects with `@id` <s1 IRI> or <s2 IRI> and `@graph` <g1 NURI> or <g2 NURI>
 *     const expenses: DeepSignal<Set<Expense>> = useShape(ExpenseShape,
 *         {graphs: ["<g1 NURI>", "<g2 NURI>"],
 *         subjects: ["<s1 NURI>", "<s2 NURI>"]});
 *
 *
 *     // Call expenses.add({"@graph": "<g1 or g2 NURI>", "@id": "", title: "Example title"}), to add new elements.
 *     // Leave `@id` an empty string to auto-generate a subject IRI (adjust your scope accordingly).
 *
 *     // Note that if you use `@id` (the subject IRI) as key, you need to ensure that it is unique within your scope.
 *     // This only affects you if you set custom subject IRIs. The auto-generated `@id`s are globally unique.
 * </script>
 *
 * <section>
 *     <div>
 *         {# if loading}
 *         <p>
 *             Loading...
 *         </p>
 *         {:else if expenses.size === 0}
 *         <p>
 *             No expense yet.
 *         </p>
 *         {:else}
 *         {#each expensesSorted as expense, index (expense['@id']) }
 *             <ExpenseCard
 *                 expense={expense}
 *             />
 *         {/each}
 *         {/if}
 *     </div>
 * </section>
 * ```
 *
 * ---
 * In the ExpenseCard component:
 * ```svelte
 *
 *   let {
 *     expense = $bindable(),
 *   }: { expense: Expense; } = $props();
 * </script>
 *
 * <div>
 *   <input
 *     bind:value={expense.title}
 *     placeholder="Expense title"
 *   />
 * </div>
 * ```
 */
const useShape = <
    ST extends ShapeType<T>,
    const CONF extends RdfOrmConfig<T>,
    T extends BaseType = ST extends ShapeType<infer T_> ? T_ : never,
    SUBSCRIPTION_DATA = SubscriptionData<T, CONF>,
>(
    shape: ST,
    conf: CONF | string | undefined
): UseShapeResult<ST, CONF, T> => {
    if (conf === undefined) {
        // @ts-ignore
        return {
            data: undefined,
            isLoading: false,
            promise: undefined,
            subscription: undefined,
        };
    }

    const parsedConf = normalizeConf(conf);

    const subscription = RdfOrmSubscription.getOrCreate(shape, parsedConf);

    onDestroy(subscription.close);

    const nextPage =
        subscription?.mode === "orderedPaginatedCumulative" ||
        subscription?.mode === "orderedPaginatedSimple"
            ? // @ts-ignore
              subscription.nextPage
            : undefined;
    const previousPage =
        subscription?.mode === "orderedPaginatedSimple"
            ? // @ts-ignore
              subscription.previousPage
            : undefined;

    // let data = $state(undefined as SUBSCRIPTION_DATA | undefined);
    let isLoading = writable(true);

    subscription.readyPromise.then(() => {
        isLoading.set(false);
    });

    const ds = useDeepSignal(subscription.signalObject);

    let data = {
        root: subscription.signalObject,
        ...ds,
    } as UseShapeStoreResult<SUBSCRIPTION_DATA>;

    let dataWhenReady = derived([isLoading, data], ([$isLoading, $data]) =>
        $isLoading ? undefined : $data
    );

    // @ts-ignore
    return {
        data: dataWhenReady,
        isLoading,
        promise: subscription.readyPromise,
        subscription,
        nextPage,
        previousPage,
    };
};

export default useShape;

type UseShapeResult_<
    ST extends ShapeType<any>,
    CONF extends RdfOrmConfig<T>,
    T extends BaseType,
    SUBSCRIPTION_DATA = SubscriptionData<T, CONF>,
> = {
    /**
     * Initializes loading of the next page.
     * This will update the data but you will not be called back on it.
     */
    nextPage: () => void;
    /**
     * Initializes loading of the previous page.
     * This will update the data but you will not be called back on it.
     */
    previousPage: () => void;
    /**
     * `true` when no data is available yet and `conf` is not `undefined`.
     *
     * It is *not* set to `true` while loading pages (through `nextPage()` or `previousPage()`.
     */
    isLoading: boolean;
    /**
     * The requested data, once loaded.
     * Depending on your orderBy config, this will either be a {@link DeepSignalSet}
     * or a [`DeepSignal<ReadOnlyArray>`]({@link DeepSignal}) (you can modify its properties and sub-objects though).
     *
     * This object is the value returned by {@link RdfOrmSubscription.signalObject}.
     */
    data: UseShapeStoreResult<SUBSCRIPTION_DATA> | undefined;
    /**
     * A promise that resolves once the data is loaded.
     * Note that if `conf` is `undefined`, this property is `undefined`.
     */
    promise: CONF extends undefined ? undefined : Promise<SUBSCRIPTION_DATA>;
    /** The underlying {@link RdfOrmSubscription} through which the data is loaded. */
    subscription: CONF extends undefined
        ? undefined
        : RdfOrmSubscriptionFor<ST, CONF, T>;
};

export type UseShapeResult<
    ST extends ShapeType<any>,
    CONF extends RdfOrmConfig<T>,
    T extends BaseType,
> = undefined extends CONF["pageSize"]
    ? Omit<UseShapeResult_<ST, CONF, T>, "nextPage" | "previousPage"> // No pagination functions.
    : undefined extends CONF["maxActivePages"]
      ? Omit<UseShapeResult_<ST, CONF, T>, "previousPage"> // Only forward pagination without `maxActivePages`.
      : UseShapeResult_<ST, CONF, T>; // Forward and backwards pagination.
