// Copyright (c) 2025 Laurin Weger, Par le Peuple, NextGraph.org developers
// All rights reserved.
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE2 or http://www.apache.org/licenses/LICENSE-2.0>
// or the MIT license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.
// SPDX-License-Identifier: Apache-2.0 OR MIT

import { normalizeScope, type Scope } from "../../types.ts";
import { onDestroy } from "svelte";
import type { BaseType, ShapeType } from "@ng-org/shex-orm";
import {
    useDeepSignal,
    type UseDeepSignalResult,
} from "@ng-org/alien-deepsignals/svelte4";
import { DeepSignalSet } from "@ng-org/alien-deepsignals";
import { OrmSubscription } from "../../connector/ormSubscriptionHandler.ts";
import { readOnlySet } from "../utils.ts";

/** Extended result including the originating root signal wrapper from shape logic. @ignore*/
export interface UseShapeStoreResult<T = object>
    extends UseDeepSignalResult<T> {
    root: any;
}

/**
 * Svelte 4 hook to subscribe to RDF data in the graph database using a shape, see {@link ShapeType}.
 *
 * Returns a {@link DeepSignalSet} store containing the objects matching the shape and that are within the scope.
 * Establishes a 2-way binding: Modifications to the object are immediately committed,
 * changes coming from the backend (or other components) cause an immediate rerender.
 *
 * @param shape The {@link ShapeType} the objects should have (generated by the shex-orm tool).
 * @param scope The {@link Scope} as graph string or scope object with graphs and subjects.
 * @returns A {@link DeepSignalSet} with the orm objects or an empty set, if still loading.\
 *          If the scope is explicitly set to `undefined`, an empty set is returned which errors
 *          if you try to make modifications on it.
 *
 * @example
 * ```svelte
 * <script lang="ts">
 *     // Gets all expense objects with `@id` <s1 IRI> or <s2 IRI> and `@graph` <g1 NURI> or <g2 NURI>
 *     const expenses: DeepSignal<Set<Expense>> = useShape(ExpenseShape,
 *         {graphs: ["<g1 NURI>", "<g2 NURI>"],
 *         subjects: ["<s1 NURI>", "<s2 NURI>"]});
 *
 *     const expensesSorted = computed(() => expenses.sort((a, b) =>
 *         a.dateOfPurchase.localeCompare(b.dateOfPurchase)
 *     ));
 *
 *     // Call expenses.add({"@graph": "<g1 or g2 NURI>", "@id": "", title: "Example title"}), to add new elements.
 *     // Leave `@id` an empty string to auto-generate a subject IRI (adjust your scope accordingly).
 *
 *     // Note that if you use `@id` (the subject IRI) as key, you need to ensure that it is unique within your scope.
 *     // If it is not (i.e. there are two graphs with the same subject), use the combination of `@graph` and `@id`.
 * </script>
 *
 * <section>
 *     <div>
 *         {# if expensesSorted.length === 0}
 *         <p>
 *             No expense yet.
 *         </p>
 *         {:else}
 *         {#each expensesSorted as expense, index (expense['@id']) }
 *             <ExpenseCard
 *                 expense={expense}
 *             />
 *         {/each}
 *         {/if}
 *     </div>
 * </section>
 * ```
 *
 * ---
 * In the ExpenseCard component:
 * ```svelte
 *
 *   let {
 *     expense = $bindable(),
 *   }: { expense: Expense; } = $props();
 * </script>
 *
 * <div>
 *   <input
 *     bind:value={expense.title}
 *     placeholder="Expense title"
 *   />
 * </div>
 * ```
 */
export function useShape<T extends BaseType>(
    shape: ShapeType<T>,
    scope: Scope | string | undefined
): UseShapeStoreResult<Set<T>> {
    if (scope === undefined) {
        const ds = useDeepSignal(readOnlySet as Set<T>);
        return { root: readOnlySet, ...ds };
    }

    const { signalObject: rootSignal, close } = OrmSubscription.getOrCreate(
        shape,
        normalizeScope(scope)
    );

    onDestroy(close);

    const ds = useDeepSignal<Set<T>>(rootSignal as Set<T>);
    return { root: rootSignal, ...ds } as UseShapeStoreResult<Set<T>>;
}

export default useShape;
