export const bcp47ByEnglishName = {
  "Abkhazian": "ab",
  "Achinese": "ace",
  "Acoli": "ach",
  "Adangme": "ada",
  "Adyghe": "ady",
  "Afar": "aa",
  "Afrihili": "afh",
  "Afrikaans": "af",
  "Ainu": "ain",
  "Akan": "ak",
  "Akkadian": "akk",
  "Albanian": "sq",
  "Aleut": "ale",
  "Alsatian": "gsw",
  "Amharic": "am",
  "Angika": "anp",
  "Arabic": "ar",
  "Aragonese": "an",
  "Arapaho": "arp",
  "Arawak": "arw",
  "Armenian": "hy",
  "Aromanian": "rup",
  "Assamese": "as",
  "Asturian": "ast",
  "Avaric": "av",
  "Avestan": "ae",
  "Awadhi": "awa",
  "Aymara": "ay",
  "Azerbaijani": "az",
  "Balinese": "ban",
  "Baluchi": "bal",
  "Bambara": "bm",
  "Basa": "bas",
  "Bashkir": "ba",
  "Basque": "eu",
  "Beja": "bej",
  "Belarusian": "be",
  "Bemba": "bem",
  "Bengali": "bn",
  "Bhojpuri": "bho",
  "Bikol": "bik",
  "Bini": "bin",
  "Bislama": "bi",
  "Blin": "byn",
  "Blissymbols": "zbl",
  "Bokmål, Norwegian": "nb",
  "Bosnian": "bs",
  "Braj": "bra",
  "Breton": "br",
  "Buginese": "bug",
  "Bulgarian": "bg",
  "Buriat": "bua",
  "Burmese": "my",
  "Caddo": "cad",
  "Catalan": "ca",
  "Cebuano": "ceb",
  "Central Khmer": "km",
  "Chagatai": "chg",
  "Chamorro": "ch",
  "Chechen": "ce",
  "Cherokee": "chr",
  "Cheyenne": "chy",
  "Chibcha": "chb",
  "Chinese": "zh",
  "Chinook jargon": "chn",
  "Choctaw": "cho",
  "Church Slavonic": "cu",
  "Chuukese": "chk",
  "Chuvash": "cv",
  "Classical Syriac": "syc",
  "Cook Islands Maori": "rar",
  "Coptic": "cop",
  "Cornish": "kw",
  "Corsican": "co",
  "Cree": "cr",
  "Creek": "mus",
  "Crimean Tatar": "crh",
  "Croatian": "hr",
  "Czech": "cs",
  "Dakota": "dak",
  "Danish": "da",
  "Dargwa": "dar",
  "Delaware": "del",
  "Dene Suline": "chp",
  "Dhivehi": "dv",
  "Dinka": "din",
  "Dogri": "doi",
  "Dogrib": "dgr",
  "Duala": "dua",
  "Dutch": "nl",
  "Dutch, Middle (ca.1050-1350)": "dum",
  "Dyula": "dyu",
  "Dzongkha": "dz",
  "Eastern Frisian": "frs",
  "Efik": "efi",
  "Egyptian (Ancient)": "egy",
  "Ekajuk": "eka",
  "Elamite": "elx",
  "English": "en",
  "English, Middle (1100-1500)": "enm",
  "English, Old (ca.450-1100)": "ang",
  "Erzya": "myv",
  "Esperanto": "eo",
  "Estonian": "et",
  "Ewe": "ee",
  "Ewondo": "ewo",
  "Fang": "fan",
  "Fanti": "ak",
  "Faroese": "fo",
  "Fijian": "fj",
  "Filipino": "fil",
  "Finnish": "fi",
  "Fon": "fon",
  "French": "fr",
  "French, Middle (ca. 1400-1600)": "frm",
  "French, Old (842-ca.1400)": "fro",
  "Friulian": "fur",
  "Fulah": "ff",
  "Haida": "hai",
  "Haitian Creole": "ht",
  "Hausa": "ha",
  "Hawaiian": "haw",
  "Hebrew": "he",
  "Herero": "hz",
  "Hiligaynon": "hil",
  "Hindi": "hi",
  "Hiri Motu": "ho",
  "Hittite": "hit",
  "Hmong": "hmn",
  "Hungarian": "hu",
  "Hupa": "hup",
  "Ga": "gaa",
  "Gaelic": "gd",
  "Galibi Carib": "car",
  "Galician": "gl",
  "Ganda": "lg",
  "Gayo": "gay",
  "Gbaya": "gba",
  "Geez": "gez",
  "Georgian": "ka",
  "German": "de",
  "German, Middle High (ca.1050-1500)": "gmh",
  "German, Old High (ca.750-1050)": "goh",
  "Gilbertese": "gil",
  "Gondi": "gon",
  "Gorontalo": "gor",
  "Gothic": "got",
  "Grebo": "grb",
  "Greek": "el",
  "Greek, Ancient (to 1453)": "grc",
  "Greenlandic": "kl",
  "Guarani": "gn",
  "Gujarati": "gu",
  "Gwich'in": "gwi",
  "Iban": "iba",
  "Icelandic": "is",
  "Ido": "io",
  "lgbo": "ig",
  "Iloko": "ilo",
  "Inari Sami": "smn",
  "Indonesian": "id",
  "Ingush": "inh",
  "Interlingua (International Auxiliary Language Association)": "ia",
  "Inuktitut": "iu",
  "Inupiaq": "ik",
  "Irish": "ga",
  "Irish, Middle (900-1200)": "mga",
  "Irish, Old (to 900)": "sga",
  "Italian": "it",
  "Japanese": "ja",
  "Javanese": "jv",
  "Jingpho": "kac",
  "Judeo-Arabic": "jrb",
  "Judeo-Persian": "jpr",
  "Kabardian": "kbd",
  "Kabyle": "kab",
  "Kalmyk": "xal",
  "Kamba": "kam",
  "Kannada": "kn",
  "Kanuri": "kr",
  "Kapampangan": "pam",
  "Karachay-Balkar": "krc",
  "Kara-Kalpak": "kaa",
  "Karelian": "krl",
  "Kashmiri": "ks",
  "Kashubian": "csb",
  "Kawi": "kaw",
  "Kazakh": "kk",
  "Khasi": "kha",
  "Khotanese": "kho",
  "Kikuyu": "ki",
  "Kimbundu": "kmb",
  "Kinyarwanda": "rw",
  "Klingon": "tlh",
  "Komi": "kv",
  "Kongo": "kg",
  "Konkani": "kok",
  "Korean": "ko",
  "Kosraean": "kos",
  "Kpelle": "kpe",
  "Kumyk": "kum",
  "Kurdish": "ku",
  "Kurukh": "kru",
  "Kutenai": "kut",
  "Kwanyama": "kj",
  "Kyrgyz": "ky",
  "Ladino": "lad",
  "Lahnda": "lah",
  "Lamba": "lam",
  "Lao": "lo",
  "Latin": "la",
  "Latvian": "lv",
  "Lezghian": "lez",
  "Limburgish": "li",
  "Lingala": "ln",
  "Lithuanian": "lt",
  "Lojban": "jbo",
  "Lower Sorbian": "dsb",
  "Lozi": "loz",
  "Luba-Katanga": "lu",
  "Luba-Lulua": "lua",
  "Luiseno": "lui",
  "Lule Sami": "smj",
  "Lunda": "lun",
  "Luo (Kenya and Tanzania)": "luo",
  "Lushai": "lus",
  "Luxembourgish": "lb",
  "Macedonian": "mk",
  "Madurese": "mad",
  "Magahi": "mag",
  "Maithili": "mai",
  "Makasar": "mak",
  "Malagasy": "mg",
  "Malay": "ms",
  "Malayalam": "ml",
  "Maltese": "mt",
  "Manchu": "mnc",
  "Mandar": "mdr",
  "Mandingo": "man",
  "Manipuri": "mni",
  "Manx": "gv",
  "Maori": "mi",
  "Mapudungun": "arn",
  "Marathi": "mr",
  "Mari": "chm",
  "Marshallese": "mh",
  "Marwari": "mwr",
  "Masai": "mas",
  "Mende": "men",
  "Mi'kmaq": "mic",
  "Minangkabau": "min",
  "Mirandese": "mwl",
  "Mohawk": "moh",
  "Moksha": "mdf",
  "Mongo": "lol",
  "Mongolian": "mn",
  "Mossi": "mos",
  "N'Ko": "nko",
  "Nahuatl languages": "nah",
  "Nauru": "na",
  "Navajo": "nv",
  "Ndebele, North": "nd",
  "Ndebele, South": "nr",
  "Ndonga": "ng",
  "Neapolitan": "nap",
  "Nepal Bhasa": "new",
  "Nepali": "ne",
  "Nias": "nia",
  "Niuean": "niu",
  "Nogai": "nog",
  "Norse, Old": "non",
  "Northern Frisian": "frr",
  "Northern Sami": "se",
  "Northern Sotho": "nso",
  "Norwegian": "no",
  "Nuosu": "ii",
  "Nyamwezi": "nym",
  "Nyanja": "ny",
  "Nyankole": "nyn",
  "Nynorsk, Norwegian": "nn",
  "Nyoro": "nyo",
  "Nzima": "nzi",
  "Occidental": "ie",
  "Occitan": "oc",
  "Occitan, Old (to 1500)": "pro",
  "Official Aramaic (700-300 BCE)": "arc",
  "Ojibwa": "oj",
  "Old Newari": "onw",
  "Oriya": "or",
  "Oromo": "om",
  "Osage": "osa",
  "Ossetic": "os",
  "Pahlavi": "pal",
  "Palauan": "pau",
  "Pali": "pi",
  "Pangasinan": "pag",
  "Papiamento": "pap",
  "Pashto": "ps",
  "Persian": "fa",
  "Persian, Old (ca.600-400 B.C.)": "peo",
  "Phoenician": "phn",
  "Pohnpeian": "pon",
  "Polish": "pl",
  "Portuguese": "pt",
  "Prakrit languages": "pra", // kept as code family tag; see exclusions too
  "Punjabi": "pa",
  "Quechua": "qu",
  "Rajasthani": "raj",
  "Rapanui": "rap",
  "Romanian": "ro",
  "Romansh": "rm",
  "Romany": "rom",
  "Rundi": "rn",
  "Russian": "ru",
  "Samaritan Aramaic": "sam",
  "Samoan": "sm",
  "Sandawe": "sad",
  "Sango": "sg",
  "Sanskrit": "sa",
  "Santali": "sat",
  "Sardinian": "sc",
  "Sasak": "sas",
  "Saxon, Low": "nds",
  "Scots": "sco",
  "Selkup": "sel",
  "Serbian": "sr",
  "Serer": "srr",
  "Shan": "shn",
  "Shona": "sn",
  "Sicilian": "scn",
  "Sidamo": "sid",
  "Siksika": "bla",
  "Sindhi": "sd",
  "Sinhalese": "si",
  "Skolt Sami": "sms",
  "Slave (Athapascan)": "den",
  "Slovak": "sk",
  "Slovenian": "sl",
  "Sogdian": "sog",
  "Somali": "so",
  "Soninke": "snk",
  "Sotho, Southern": "st",
  "Southern Altai": "alt",
  "Southern Sami": "sma",
  "Spanish": "es",
  "Sranan Tongo": "srn",
  "Sukuma": "suk",
  "Sumerian": "sux",
  "Sundanese": "su",
  "Susu": "sus",
  "Swahili": "sw",
  "Swati": "ss",
  "Swedish": "sv",
  "Syriac": "syr",
  "Tagalog": "tl",
  "Tahitian": "ty",
  "Tajik": "tg",
  "Tamashek": "tmh",
  "Tamil": "ta",
  "Tatar": "tt",
  "Telugu": "te",
  "Tereno": "ter",
  "Tetum": "tet",
  "Thai": "th",
  "Tibetan": "bo",
  "Tigre": "tig",
  "Tigrinya": "ti",
  "Timne": "tem",
  "Tiv": "tiv",
  "Tlingit": "tli",
  "Tokelau": "tkl",
  "Tok Pisin": "tpi",
  "Tonga (Nyasa)": "tog",
  "Tonga (Tonga Islands)": "to",
  "Tsimshian": "tsi",
  "Tsonga": "ts",
  "Tswana": "tn",
  "Tumbuka": "tum",
  "Turkish": "tr",
  "Turkish, Ottoman (1500-1928)": "ota",
  "Turkmen": "tk",
  "Tuvalu": "tvl",
  "Tuvinian": "tyv",
  "Twi": "tw",
  "Udmurt": "udm",
  "Ugaritic": "uga",
  "Ukrainian": "uk",
  "Umbundu": "umb",
  "Upper Sorbian": "hsb",
  "Urdu": "ur",
  "Uyghur": "ug",
  "Uzbek": "uz",
  "Vai": "vai",
  "Venda": "ve",
  "Vietnamese": "vi",
  "Volapük": "vo",
  "Votic": "vot",
  "Walloon": "wa",
  "Waray": "war",
  "Washo": "was",
  "Welsh": "cy",
  "Western Frisian": "fy",
  "Wolaytta": "wal",
  "Wolof": "wo",
  "Xhosa": "xh",
  "Yakut": "sah",
  "Yao": "yao",
  "Yapese": "yap",
  "Yiddish": "yi",
  "Yoruba": "yo",
  "Zapotec": "zap",
  "Zazaki": "zza",
  "Zenaga": "zen",
  "Zhuang": "za",
  "Zulu": "zu",
  "Zuni": "zun"
};

export const bcp47Exclusions = [
  // language families / collectives / ambiguous labels
  "Afro-Asiatic languages",
  "Algonquian languages",
  "Altaic languages",
  "Artificial languages",
  "Athapascan languages",
  "Australian languages",
  "Austronesian languages",
  "Baltic languages",
  "Bamileke languages",
  "Banda languages",
  "Bantu languages",
  "Batak languages",
  "Berber languages",
  "Bihari languages",
  "Caucasian languages",
  "Celtic languages",
  "Central American Indian languages",
  "Chamic languages",
  "Creoles and pidgins",
  "Creoles and pidgins, English-based",
  "Creoles and pidgins, French-based",
  "Creoles and pidgins, Portuguese-based",
  "Cushitic languages",
  "Dravidian languages",
  "Finno-Ugrian languages",
  "Germanic languages",
  "Himachali languages",
  "Iroquoian languages",
  "Indic languages",
  "Indo-European languages",
  "Iranian languages",
  "Ijo languages", // your list had "ljo languages"
  "Karen languages",
  "Khoisan languages",
  "Kru languages",
  "Land Dayak languages",
  "Manobo languages",
  "Mayan languages",
  "Mon-Khmer languages",
  "Munda languages",
  "Niger-Kordofanian languages",
  "Nilo-Saharan languages",
  "North American Indian languages",
  "Nubian languages",
  "Otomian languages",
  "Papuan languages",
  "Philippine languages",
  "Prakrit languages", // family; individual tags exist but label is collective
  "Romance languages",
  "Salishan languages",
  "Sami languages",
  "Semitic languages",
  "Sign Languages",
  "Sino-Tibetan languages",
  "Siouan languages",
  "Slavic languages",
  "Songhai languages",
  "Sorbian languages",
  "South American Indian languages",
  "Tai languages",
  "Tupi languages",
  "Wakashan languages",
  "Yupik languages",
  "Zande languages"
];

const norm = (s: string) => s.replace(/\s+/g, " ").trim().toLowerCase();
const NAME_TO_CODE = new Map(Object.entries(bcp47ByEnglishName).map(([n, c]) => [norm(n), c]));
const CODE_TO_NAME = Object.fromEntries(Object.entries(bcp47ByEnglishName).map(([n, c]) => [c, n]));
const dnLang = new Intl.DisplayNames(['en'], {type: 'language', languageDisplay: 'dialect'});

export function codeByLanguageName(name: string) {
  return NAME_TO_CODE.get(norm(name)) ?? null;
}

export function languageNameByCode(code: string | { "@id": string }) {
  if (!code) return null;
  try {
    //TODO: check if code is array, sometimes happens with IRI ldo
    const codeWithoutPrefix = typeof code === "string" ? code : code["@id"].replace("did:ng:k:language:", "");
    const canon = Intl.getCanonicalLocales(codeWithoutPrefix)[0];
    return dnLang.of(canon) || CODE_TO_NAME[canon] || canon; // fallback to our map, then echo
  } catch (e) {
    console.error(e);
    return typeof code === "string" ? code : null;
  }
}

export function codeIRIByLanguageName(name: string) {
  const code = codeByLanguageName(name);
  if (!code) return null;
  return bcpCodeToIRI(code);
}

export function bcpCodeToIRI(code: string) {
  if (!code) return null;
  return {
    ["@id"]: "did:ng:k:language:" + code.toLowerCase(),
  }
}